# Site settings
title: DBSec18
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dbsec18.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Check gems allowed on github pages here: https://pages.github.com/versions/
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

exclude: ['CNAME', 'README.md']
